name: Build DMG

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Install dmgbuild
        run: pip3 install dmgbuild

      - name: Build app
        run: npm run build

      - name: Create DMG
        run: dmgbuild -D app='web-tracker.app' "web-tracker" web-tracker.dmg

      - name: List directory contents
        run: ls -al

      - name: Upload DMG artifact
        uses: actions/upload-artifact@v2
        with:
          name: web-tracker
          path: web-tracker.dmg

      - name: Download DMG artifact
        uses: actions/download-artifact@v2
        with:
          name: web-tracker
          path: downloaded-artifacts

      - name: List downloaded artifacts
        run: ls -al downloaded-artifacts
