name: Build DMG

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Install dmgbuild
        run: pip3 install dmgbuild

      - name: Build app
        run: npm run build

      - name: Create DMG
        run: dmgbuild -s web-tracker -d "web-tracker" -v 1.0.0 -i web-tracker.app -o web-tracker.dmg
