name: Install dmgbuild

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest # Define the operating system for the workflow
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2 # Checkout the repository
    
    - name: Install dmgbuild
      run: pip3 install dmgbuild # Run the pip3 install command to install dmgbuild
